modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="time"
version="1.0.0"
displayName="The Tale Of The Infinite Macrocosm's Universe And Time"
credits="“你有]有想^你的Minecraft世界的^去或未?硎鞘谗幼拥哪兀窟@_l中的模M’rg髡f（The Infinite Macrocosm's Universe And Time：Time of Saga）‘可以你??F@望！在@e你可以建造r光C，探索10rg，^去F在c未?恚? 未?砑船F在！” @是一群主的自制模M，目前凫对缙陂_lA段。以後模M一些更新就在@e放出?~ Minecraft[虬姹荆1.15.2 制作件：它使用了Eclipse?建代a，用BlockBench、雪松?建模型（本模M有一些部分【主要是S度】使用了模M制作器Mcreator以保C模M的更新速度，但@?K不代表它劣|！） 更新情r：永不坑！ _lF（目前）:EN_JIA(Mod整w制作)、N~X（模M`感大{、美g提供者）天{色的苦力怕（美g提供）、墨懿老??子（美g提供）、蓝天（`感提供者）、黑夜中的^（美g提供者）。 `感?碓矗r光CMod、暮色森林Mod、UndertaleMod以及Creepypastac空工Mod 感x：IETLORD（幻想l的邪王真眼使熵）、那些我走M模M制作界的前 @只是群主人作品！大家期望值不要太高！ 想加M模M什麽|西可以告V我！（只要我能做得到-- 即使你X得模M垃圾也不要！可以模M的改M！ 注意：目前模M]有y伺服器！"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="EN_JIA/天蓝色的苦力怕/鲮鱼x（空白/蓝天"
description='''
A mod about the time.
'''

[[dependencies.time]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




